name: CI

on:
  pull_request:
    paths:
      - "src/**"
      - "**/*.gradle"
      - "**/*.gradle.kts"
      - "gradle.properties"
      - "gradle/**"
      - "gradlew"
      - "gradlew.bat"
      - "checks.xml"
      - ".github/workflows/java-ci.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "**/*.gradle"
      - "**/*.gradle.kts"
      - "gradle.properties"
      - "gradle/**"
      - "gradlew"
      - "gradlew.bat"
      - "checks.xml"
      - ".github/workflows/java-ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Review Service
    uses: spring-divas/common/.github/workflows/java-ci.yml@main
    permissions:
      contents: write
      checks: write
      pull-requests: read

